export const COMPONENT_IDS = {
  /* NavBar */
  NAVBAR_HOME_PAGE: 'navbar-home-page',
  NAVBAR_LANDING_PAGE: 'navbar-landing-page',
  NAVBAR_ABOUT_PAGE: 'navbar-about-page',
  NAVBAR_FAQ_PAGE: 'navbar-faq',
  NAVBAR_SUBSCRIBE_PAGE: 'navbar-subscribe',
  NAVBAR_EVENTS_PAGE: 'navbar-events-page',
  NAVBAR_CURRENT_USER: 'navbar-current-user',
  NAVBAR_COLLAPSE: 'navbar-collapse',
  NAVBAR_LOGIN_DROPDOWN: 'navbar-login-dropdown',
  NAVBAR_LOGIN_DROPDOWN_SIGN_IN: 'navbar-login-dropdown-sign-in',
  NAVBAR_LOGIN_DROPDOWN_SIGN_UP: 'navbar-login-dropdown-sign-up',
  NAVBAR_LOGIN_DROPDOWN_SIGN_UP_ORGANIZATION: 'navbar-login-dropdown-sign-up-organization',
  NAVBAR_MANAGE_DROPDOWN: 'navbar-manage-dropdown',
  NAVBAR_MANAGE_DROPDOWN_DATABASE: 'navbar-manage-dropdown-database',
  NAVBAR_DASHBOARD_PAGE: 'navbar-dashboard',
  NAVBAR_ADD_EVENT_PAGE: 'navbar_add_event_page',
  NAVBAR_MY_EVENTS_PAGE: 'navbar-my-events',
  NAVBAR_ADMIN_EVENT_MODERATION_PAGE: 'navbar-admin-event-moderation',
  NAVBAR_ADMIN_ORGANIZATION_MODERATION_PAGE: 'navbar-admin-organization-moderation',
  NAVBAR_ADMIN_USER_MODERATION_PAGE: 'navbar-admin-user-moderation',
  NAVBAR_ADMIN_REVIEW_MODERATION_PAGE: 'navbar-admin-review-moderation',
  MANAGE_DATABASE_DUMP: 'manage-database-dump',
  NAVBAR_SIGN_OUT_PAGE: 'navbar-sign-out',
  NAVBAR_USER_PROFILE_PAGE: 'navbar-user-profile',

  SIGN_IN_FORM_EMAIL: 'sign-in-form-email',
  SIGN_IN_FORM_PASSWORD: 'sign-in-form-password',
  SIGN_IN_FORM_SUBMIT: 'sign-in-form-submit',
  SIGN_UP_FORM_FIRST_NAME: 'sign-up-form-first-name',
  SIGN_UP_FORM_LAST_NAME: 'sign-up-form-last-name',
  SIGN_UP_FORM_EMAIL: 'sign-up-form-email',
  SIGN_UP_FORM_PASSWORD: 'sign-up-form-password',
  SIGN_UP_FORM_ORGANIZATION_ID: 'sign-up-form-organization-id',
  SIGN_UP_FORM_NAME: 'sign-up-form-name',
  SIGN_UP_FORM_SUBMIT: 'sign-up-form-submit',

  ADD_EVENT_FORM_TITLE: 'add-event-form-title',
  ADD_EVENT_FORM_IMAGE: 'add-event-form-image',
  ADD_EVENT_FORM_DESCRIPTION: 'add-event-form-description',
  ADD_EVENT_FORM_IMPACT: 'add-event-form-impact',
  ADD_EVENT_FORM_TOTAL_SPOTS: 'add-event-form-total-spots',
  ADD_EVENT_FORM_ACTIVITY_TYPE: 'add-event-form-activity-type',
  ADD_EVENT_FORM_MAINCATEGORY: 'add-event-form-maincategory',
  ADD_EVENT_FORM_SUBCATEGORY: 'add-event-form-subcategory',
  ADD_EVENT_FORM_HOSTED_BY: 'add-event-form-hosted-by',
  ADD_EVENT_FORM_HOST_TYPE: 'add-event-form-host-type',
  ADD_EVENT_FORM_HOST_PHONE: 'add-event-form-host-phone',
  ADD_EVENT_FORM_ADDRESS: 'add-event-form-address',
  ADD_EVENT_FORM_ZIPCODE: 'add-event-form-zipcode',
  ADD_EVENT_FORM_CITY: 'add-event-form-city',
  ADD_EVENT_FORM_STATE: 'add-event-form-state',
  ADD_EVENT_FORM_COUNTRY: 'add-event-form-country',
  ADD_EVENT_FORM_START_DATE: 'add-event-form-start-date',
  ADD_EVENT_FORM_END_DATE: 'add-event-form-end-date',
  ADD_EVENT_FORM_FREQUENCY: 'add-event-form-frequency',
  ADD_EVENT_FORM_REQUIRED_SKILLS: 'add-event-form-required-skills',
  ADD_EVENT_FORM_ACCESSIBILITIES: 'add-event-form-accessibilities',
  ADD_EVENT_FORM_NEXT_PAGE: 'add-event-form-next-page',
  ADD_EVENT_FORM_PREVIOUS_PAGE: 'add-event-form-previous-page',
  ADD_EVENT_FORM_SUBMIT: 'add-event-form-submit',
  ADD_EVENT_FORM_SHOW_LOCATION: 'add-event-form-show-location',

  EDIT_EVENT_FORM_TITLE: 'edit-event-form-title',
  EDIT_EVENT_FORM_IMAGE: 'edit-event-form-image',
  EDIT_EVENT_FORM_DESCRIPTION: 'edit-event-form-description',
  EDIT_EVENT_FORM_IMPACT: 'edit-event-form-impact',
  EDIT_EVENT_FORM_TOTAL_SPOTS: 'edit-event-form-total-spots',
  EDIT_EVENT_FORM_ACTIVITY_TYPE: 'edit-event-form-activity-type',
  EDIT_EVENT_FORM_MAINCATEGORY: 'edit-event-form-maincategory',
  EDIT_EVENT_FORM_SUBCATEGORY: 'edit-event-form-subcategory',
  EDIT_EVENT_FORM_HOSTED_BY: 'edit-event-form-hosted-by',
  EDIT_EVENT_FORM_HOST_TYPE: 'edit-event-form-host-type',
  EDIT_EVENT_FORM_HOST_PHONE: 'edit-event-form-host-phone',
  EDIT_EVENT_FORM_ADDRESS: 'edit-event-form-address',
  EDIT_EVENT_FORM_ZIPCODE: 'edit-event-form-zipcode',
  EDIT_EVENT_FORM_CITY: 'edit-event-form-city',
  EDIT_EVENT_FORM_STATE: 'edit-event-form-state',
  EDIT_EVENT_FORM_COUNTRY: 'edit-event-form-country',
  EDIT_EVENT_FORM_START_DATE: 'edit-event-form-start-date',
  EDIT_EVENT_FORM_END_DATE: 'edit-event-form-end-date',
  EDIT_EVENT_FORM_FREQUENCY: 'edit-event-form-frequency',
  EDIT_EVENT_FORM_REQUIRED_SKILLS: 'edit-event-form-required-skills',
  EDIT_EVENT_FORM_ACCESSIBILITIES: 'edit-event-form-accessibilities',
  EDIT_EVENT_FORM_SUBMIT: 'edit-event-form-submit',
  EDIT_EVENT_FORM_DELETE: 'edit-event-form-delete',
  EDIT_EVENT_FORM_CANCEL: 'edit-event-form-cancel',
  EDIT_EVENT_FORM_CONFIRM_DELETE: 'edit-event-form-confirm-delete',

  EVENTS_SEARCHBAR: 'events-searchbar',
  UPCOMING_EVENT_CARD_FIND_EVENTS: 'upcoming-event-card-find-events',
  USER_DASHBOARD_VIEW_PROFILE: 'user-dashboard-view-profile',
  USER_DASHBOARD_EDIT_PROFILE: 'user-dashboard-edit-profile',
  USER_DASHBOARD_VIEW_QR_CODE: 'user-dashboard-view-qr-code',
  USER_PROFILE_EDIT_PROFILE: 'user-profile-edit-profile',

  EDIT_USER_PROFILE_FIRST_NAME: 'edit-user-profile-first-name',
  EDIT_USER_PROFILE_LAST_NAME: 'edit-user-profile-last-name',
  EDIT_USER_PROFILE_PROFILE_PICTURE_URL: 'edit-user-profile-profile-picture-url',
  EDIT_USER_PROFILE_ADDRESS: 'edit-user-profile-address',
  EDIT_USER_PROFILE_PHONE: 'edit-user-profile-phone',
  EDIT_USER_PROFILE_EMAIL: 'edit-user-profile-email',
  EDIT_USER_PROFILE_CITY: 'edit-user-profile-city',
  EDIT_USER_PROFILE_STATE: 'edit-user-profile-state',
  EDIT_USER_PROFILE_COUNTRY: 'edit-user-profile-country',
  EDIT_USER_PROFILE_ZIP_CODE: 'edit-user-profile-zip-code',
  EDIT_USER_PROFILE_SUBMIT: 'edit-user-profile-submit',

  ORGANIZATION_OVERVIEW_VIEW_PROFILE: 'organization-overview-view-profile',
  ORGANIZATION_OVERVIEW_EDIT_PROFILE: 'organization-overview-edit-profile',
  ORGANIZATION_OVERVIEW_ORG_NAME: 'organization-overview-org-name',
  ORGANIZATION_OVERVIEW_CONTACT_EMAIL: 'organization-overview-contact-email',

  ORGANIZATION_DROPDOWN: 'organization-dropdown',
  ORG_EVENT_CARD: 'org-event-card',
  ORG_EVENT_CARD_VIEW: 'org-event-card-view',
  ORG_EVENT_CARD_EDIT: 'org-event-card-edit',
  ORG_EVENT_CARD_RECORD: 'org-event-card-record',

  ORGANIZATION_PROFILE_EDIT_PROFILE: 'organization-profile-edit-profile',

  EDIT_ORGANIZATION_PROFILE_NAME: 'edit-organization-profile-name',
  EDIT_ORGANIZATION_PROFILE_IMAGE: 'edit-organization-profile-image',
  EDIT_ORGANIZATION_PROFILE_MISSION: 'edit-organization-profile-mission',
  EDIT_ORGANIZATION_PROFILE_TYPE: 'edit-organization-profile-type',
  EDIT_ORGANIZATION_PROFILE_PHONE: 'edit-organization-profile-phone',
  EDIT_ORGANIZATION_PROFILE_CONTACT_EMAIL: 'edit-organization-profile-contact-email',
  EDIT_ORGANIZATION_PROFILE_HAS_PHYSICAL_ADDRESS: 'edit-organization-profile-has-physical-address',
  EDIT_ORGANIZATION_PROFILE_ADDRESS: 'edit-organization-profile-address',
  EDIT_ORGANIZATION_PROFILE_CITY: 'edit-organization-profile-city',
  EDIT_ORGANIZATION_PROFILE_STATE: 'edit-organization-profile-state',
  EDIT_ORGANIZATION_PROFILE_ZIP_CODE: 'edit-organization-profile-zip-code',
  EDIT_ORGANIZATION_PROFILE_COUNTRY: 'edit-organization-profile-country',
  EDIT_ORGANIZATION_PROFILE_SUBMIT: 'edit-organization-profile-submit',
  EDIT_ORGANIZATION_PROFILE_RETURN_TO_DASHBOARD: 'edit-organization-profile-return-to-dashboard',

  ADMIN_HOME_PAGE: 'admin-home-page',
  ADMIN_HOME_EVENT_MODERATION: 'admin-home-event-moderation',
  ADMIN_HOME_ORGANIZATION_MODERATION: 'admin-home-organization-moderation',
  ADMIN_HOME_USER_MODERATION: 'admin-home-user-moderation',

  TOS_MODAL_OPEN: 'tos-modal-open',
  TOS_MODAL_ACCEPT: 'tos-modal-accept',
  TOS_MODAL_DECLINE: 'tos-modal-decline',
};
