/** Define ids for each page. */
export const PAGE_IDS = {
  LANDING: 'landing',
  HOME_PAGE: 'home-page',
  DASHBOARD: 'dashboard',
  MANAGE_DATABASE: 'manage-database',
  ABOUT: 'about',
  EVENTS: 'events',
  VIEW_EVENT: 'view-event',
  NOT_AUTHORIZED: 'not-authorized',
  NOT_FOUND: 'not-found',
  ADD_EVENT: 'add-event',
  EDIT_EVENT: 'edit-event',
  SIGN_IN: 'sign-in',
  SIGN_OUT: 'sign-out',
  SIGN_UP: 'sign-up',
  SIGN_UP_ORGANIZATION: 'sign-up-organization',
  FAQ: 'faq',
  USER_PROFILE: 'user-profile',
  EDIT_USER_PROFILE: 'edit-user-profile',
  USER_VIEW_ORG_PROFILE: 'user-view-org-profile',
  ORGANIZATION_PROFILE: 'organization-profile',
  EDIT_ORGANIZATION_PROFILE: 'edit-organization-profile',
  ORG_SCAN_QR: 'org-scan-qr',
};
